# Generated by Django 2.2.1 on 2019-05-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190510_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dateTime',
        ),
    ]
