# Generated by Django 2.2.1 on 2019-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
