# Generated by Django 2.2.1 on 2019-05-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='poster',
        ),
    ]
