# Generated by Django 2.2.1 on 2019-05-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_allow_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='allow_comments',
        ),
    ]
