# Generated by Django 2.2.1 on 2019-05-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_allow_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='user',
        ),
    ]
