# Generated by Django 2.2.2 on 2019-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190524_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profilePicture', models.ImageField(upload_to='media/images/')),
            ],
        ),
    ]
