# Generated by Django 2.2.2 on 2019-06-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pageeditor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
